// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/init.js";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/replicache-pull.js";
import * as $4 from "./routes/api/replicache-push.js";
import * as $5 from "./routes/hello-replicache.jsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/poke.js";
import * as $$0 from "./islands/Chat.jsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/init.js": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/replicache-pull.js": $3,
    "./routes/api/replicache-push.js": $4,
    "./routes/hello-replicache.jsx": $5,
    "./routes/index.tsx": $6,
    "./routes/poke.js": $7,
  },
  islands: {
    "./islands/Chat.jsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
